const GET_RESTAURANTS_REQUEST = 'GET_RESTAURANTS_REQUEST'
 const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS'
 const GET_RESTAURANTS_FAIL = 'GET_RESTAURANTS_FAIL'
 const GET_RESTAURANTS_RESET = 'GET_RESTAURANTS_RESET'

 const CLEAR_ERRORS = 'CLEAR_ERRORS'

 const GET_RESTAURANTDETAIL_REQUEST = 'GET_RESTAURANTDETAIL_REQUEST'
 const GET_RESTAURANTDETAIL_SUCCESS = 'GET_RESTAURANTDETAIL_SUCCESS'
 const GET_RESTAURANTDETAIL_FAIL = 'GET_RESTAURANTDETAIL_FAIL'
 const GET_RESTAURANTDETAIL_RESET = 'GET_RESTAURANTDETAIL_RESET'

 const ADD_MENUTO_CART = 'ADD_MENUTO_CART'

 const CLEAR_CART = 'CLEAR_CART'

 export {
    GET_RESTAURANTS_REQUEST,
    GET_RESTAURANTS_FAIL,
    GET_RESTAURANTS_SUCCESS,
    GET_RESTAURANTS_RESET,
    GET_RESTAURANTDETAIL_REQUEST,
    GET_RESTAURANTDETAIL_RESET,
    GET_RESTAURANTDETAIL_SUCCESS,
    GET_RESTAURANTDETAIL_FAIL,
    CLEAR_ERRORS,
    ADD_MENUTO_CART,
    CLEAR_CART
 }